# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Sledge-Plugin-BeforeOutput
version:      0.03
author: syushi matsumoto <matsumoto@alink.co.jp>
build_requires:
  Test::More: 0
  Class::Trigger: 0
  Sledge::Pages::Base: 0
license: perl
version_from: lib/Sledge/Plugin/BeforeOutput.pm
installdirs:  site
distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17

